{
 "title": "Home",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "clickhouse: rate(container_cpu_usage_seconds_total)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"dw-clickhouse-clickhouse-1\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "clickhouse: container_memory_usage_bytes (MB)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"dw-clickhouse-clickhouse-1\"} / 1e6",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "prefect-postgres: rate(container_cpu_usage_seconds_total)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"dw-analytics-prefect-postgres-1\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "prefect-postgres: container_memory_usage_bytes (MB)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"dw-analytics-prefect-postgres-1\"} / 1e6",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "prefect-server: rate(container_cpu_usage_seconds_total)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"dw-analytics-prefect-server-1\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "prefect-server: container_memory_usage_bytes (MB)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"dw-analytics-prefect-server-1\"} / 1e6",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cli: rate(container_cpu_usage_seconds_total)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"dw-analytics-cli-1\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cli: container_memory_usage_bytes (MB)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"dw-analytics-cli-1\"} / 1e6",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}